#!/usr/bin/env bash
#
# abox release script.
#
# Bumps the workspace version, verifies that attestation stamps from the
# pre-release pipeline are present and valid, generates a changelog entry,
# builds the release binary, and commits + tags the result.
#
# Usage:
#   ./scripts/release.sh 0.2.0                       # bump to 0.2.0
#   ./scripts/release.sh 0.2.0 --dry                 # show what would happen, don't commit
#   ./scripts/release.sh 0.2.0 --skip-attestation    # skip attestation verification
#
# Prerequisites:
#   - Clean git working tree (no uncommitted changes)
#   - Attestation stamps at .abox-attestations/{bench,runtime,smoke}.json
#     (generated by `just pre-release`)
#   - just, cargo, python3
#
# The script does NOT push. After it completes, review the commit and run:
#   git push origin main --tags

set -euo pipefail

# ─── Argument parsing ─────────────────────────────────────────────────────────
VERSION=""
DRY_RUN=0
SKIP_ATTESTATION=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry|--dry-run) DRY_RUN=1; shift ;;
        --skip-attestation) SKIP_ATTESTATION=1; shift ;;
        --help|-h)
            cat <<EOF
Usage: $(basename "$0") <version> [--dry] [--skip-attestation]

  <version>            Semver version to release (e.g. 0.2.0)
  --dry                Show what would happen without committing or tagging
  --skip-attestation   Skip attestation stamp verification (use with caution)
  -h, --help           This message

Steps performed:
  1.  Validate version format and working tree cleanliness
  2.  Verify attestation stamps (.abox-attestations/{bench,runtime,smoke}.json)
  3.  Bump workspace version in Cargo.toml + Cargo.lock
  4.  cargo build --release
  5.  Generate CHANGELOG.md entry from git log since last tag
  6.  cargo install --path crates/abox-cli (refresh local binary)
  7.  Commit version bump + changelog
  8.  Tag v<version>

Quality checks (fmt, clippy, test), Criterion microbenchmarks, the live
runtime e2e suite, and the agent smoke tests are covered by the attestation
stamps. Run
\`just pre-release\` before releasing to generate them.

Does NOT push. Review the commit, then:
  git push origin main --tags
EOF
            exit 0
            ;;
        *)
            if [[ -z "$VERSION" ]]; then
                VERSION="$1"; shift
            else
                echo "ERROR: unexpected argument: $1" >&2; exit 1
            fi
            ;;
    esac
done

if [[ -z "$VERSION" ]]; then
    echo "ERROR: version argument required. Usage: $(basename "$0") <version>" >&2
    exit 1
fi

# Validate semver format (major.minor.patch, optional -pre).
if ! echo "$VERSION" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.]+)?$'; then
    echo "ERROR: '$VERSION' is not valid semver (expected N.N.N or N.N.N-pre)" >&2
    exit 1
fi

# ─── Preamble ─────────────────────────────────────────────────────────────────
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"
ATTESTATION_DIR="$REPO_ROOT/.abox-attestations"

OLD_VERSION=$(grep -m1 '^version = ' Cargo.toml | sed 's/.*"\(.*\)"/\1/')
LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

echo "━━━ abox release $OLD_VERSION → $VERSION ━━━"
echo "  repo:     $REPO_ROOT"
echo "  last tag: ${LAST_TAG:-<none>}"
echo "  dry run:  $DRY_RUN"
echo

# ─── Step 1: Preflight checks ────────────────────────────────────────────────
echo "[1/10] Preflight checks..."

if [[ "$DRY_RUN" == "0" ]] && [[ -n "$(git status --porcelain)" ]]; then
    echo "ERROR: working tree is dirty. Commit or stash your changes first." >&2
    git status --short >&2
    exit 1
fi

if git rev-parse "v$VERSION" >/dev/null 2>&1; then
    echo "ERROR: tag v$VERSION already exists." >&2
    exit 1
fi

echo "  ✓ clean tree, tag v$VERSION available"

# ─── Step 2: Verify attestation stamps ───────────────────────────────────────
echo "[2/8] Verifying attestation stamps..."

if [[ "$SKIP_ATTESTATION" == "1" ]]; then
    echo "  ┌──────────────────────────────────────────────────────────┐"
    echo "  │  WARNING: --skip-attestation set — stamps NOT verified  │"
    echo "  │  Quality checks and e2e suites may be stale             │"
    echo "  └──────────────────────────────────────────────────────────┘"
else
    HEAD_SHA=$(git rev-parse --short HEAD)
    ATTEST_OK=1

    for stamp_name in bench runtime smoke; do
        stamp_file="$ATTESTATION_DIR/${stamp_name}.json"

        if [[ ! -f "$stamp_file" ]]; then
            echo "  ✗ ${stamp_name}: missing ($stamp_file)" >&2
            ATTEST_OK=0
            continue
        fi

        stamp_sha=$(python3 -c "import json; print(json.load(open('$stamp_file'))['git_sha'])")
        stamp_dirty=$(python3 -c "import json; print(json.load(open('$stamp_file'))['git_dirty'])")
        stamp_result=$(python3 -c "import json; print(json.load(open('$stamp_file'))['result'])")

        errors=""
        if [[ "$stamp_sha" != "$HEAD_SHA" ]]; then
            errors+="sha mismatch (stamp=$stamp_sha, HEAD=$HEAD_SHA) "
        fi
        if [[ "$stamp_dirty" != "False" ]]; then
            errors+="dirty tree "
        fi
        if [[ "$stamp_result" != "pass" ]]; then
            errors+="result=$stamp_result "
        fi

        if [[ -n "$errors" ]]; then
            echo "  ✗ ${stamp_name}: ${errors}" >&2
            ATTEST_OK=0
        else
            echo "  ✓ ${stamp_name}: pass (sha=$stamp_sha)"
        fi
    done

    if [[ "$ATTEST_OK" == "0" ]]; then
        echo >&2
        echo "ERROR: attestation verification failed." >&2
        echo "Run \`just pre-release\` on a clean tree at HEAD, then retry." >&2
        echo "Or pass --skip-attestation to bypass (not recommended)." >&2
        exit 1
    fi
fi

# Note: quality checks (cargo fmt/clippy/test), Criterion benchmarks, and e2e
# suites are covered by the attestation stamps (bench, runtime, smoke) verified
# above.

# ─── Step 3: Bump version ────────────────────────────────────────────────────
echo "[3/8] Bumping version $OLD_VERSION → $VERSION..."

sed -i "0,/^version = \"$OLD_VERSION\"/s//version = \"$VERSION\"/" Cargo.toml
# Regenerate Cargo.lock with the new version.
cargo generate-lockfile --quiet 2>/dev/null || cargo check --quiet 2>/dev/null
echo "  ✓ Cargo.toml + Cargo.lock updated"

# ─── Step 4: Release build ───────────────────────────────────────────────────
echo "[4/8] Building release binary..."
cargo build --workspace --release --quiet
BINARY_SIZE=$(du -h target/release/abox | cut -f1)
echo "  ✓ target/release/abox ($BINARY_SIZE)"

# ─── Step 5: Generate changelog entry ─────────────────────────────────────────
echo "[5/8] Generating changelog entry..."

if [[ -n "$LAST_TAG" ]]; then
    LOG_RANGE="${LAST_TAG}..HEAD"
else
    LOG_RANGE="HEAD"
fi

# Categorize commits by conventional-commit prefix.
CHANGELOG_ENTRY="## v${VERSION} — $(date +%Y-%m-%d)

"
for prefix_label in "feat:Features" "fix:Fixes" "refactor:Refactoring" "test:Testing" "ci:CI" "docs:Documentation" "style:Style" "chore:Chores"; do
    prefix="${prefix_label%%:*}"
    label="${prefix_label##*:}"
    commits=$(git log --oneline "$LOG_RANGE" --grep="^${prefix}" --format="- %s (%h)" 2>/dev/null || true)
    if [[ -n "$commits" ]]; then
        CHANGELOG_ENTRY+="### ${label}

${commits}

"
    fi
done

# Catch any commits that don't match a prefix.
uncategorized=$(git log --oneline "$LOG_RANGE" --format="- %s (%h)" 2>/dev/null | \
    grep -v '^\- feat\|^\- fix\|^\- refactor\|^\- test\|^\- ci\|^\- docs\|^\- style\|^\- chore' || true)
if [[ -n "$uncategorized" ]]; then
    CHANGELOG_ENTRY+="### Other

${uncategorized}

"
fi

if [[ -f CHANGELOG.md ]]; then
    # Prepend the new entry after the first line (the # title).
    python3 - CHANGELOG.md "$CHANGELOG_ENTRY" <<'PYEOF'
import sys
path, entry = sys.argv[1], sys.argv[2]
with open(path) as f:
    content = f.read()
# Insert after the first heading line.
lines = content.split("\n", 1)
if len(lines) == 2:
    content = lines[0] + "\n\n" + entry + lines[1]
else:
    content = lines[0] + "\n\n" + entry
with open(path, "w") as f:
    f.write(content)
PYEOF
else
    cat > CHANGELOG.md <<CLEOF
# Changelog

All notable changes to abox are documented here.
Format: [Keep a Changelog](https://keepachangelog.com/en/1.1.0/).

${CHANGELOG_ENTRY}
CLEOF
fi
echo "  ✓ CHANGELOG.md updated"

# ─── Step 6: Refresh local install ───────────────────────────────────────────
echo "[6/8] Installing release binary to ~/.cargo/bin..."
cargo install --path crates/abox-cli --quiet 2>/dev/null || cargo install --path crates/abox-cli
echo "  ✓ $(abox --version)"

# ─── Step 7: Commit ──────────────────────────────────────────────────────────
echo "[7/8] Committing..."
if [[ "$DRY_RUN" == "1" ]]; then
    echo "  ⊘ dry run — skipping commit"
    git diff --stat
else
    git add Cargo.toml Cargo.lock CHANGELOG.md
    git commit -m "$(cat <<EOF
release: v${VERSION}

Version bump ${OLD_VERSION} → ${VERSION}.
Changelog entry generated from commits since ${LAST_TAG:-initial commit}.
EOF
)"
    echo "  ✓ committed"
fi

# ─── Step 8: Tag ─────────────────────────────────────────────────────────────
echo "[8/8] Tagging v${VERSION}..."
if [[ "$DRY_RUN" == "1" ]]; then
    echo "  ⊘ dry run — skipping tag"
else
    git tag -a "v${VERSION}" -m "Release v${VERSION}"
    echo "  ✓ tagged v${VERSION}"
fi

# ─── Summary ──────────────────────────────────────────────────────────────────
echo
echo "━━━ release v${VERSION} ready ━━━"
echo
echo "  commit: $(git rev-parse --short HEAD)"
echo "  tag:    v${VERSION}"
echo "  binary: target/release/abox ($BINARY_SIZE)"
echo
echo "Review the commit, then push:"
echo "  git push origin main --tags"
if [[ "$DRY_RUN" == "1" ]]; then
    echo
    echo "(This was a dry run. No commits or tags were created.)"
    echo "To undo the version bump: git checkout Cargo.toml Cargo.lock"
fi
