//! Host-owned map from abox environment profiles to pinned OCI guest images.
//!
//! Repositories select a *profile* (`[environment] profile = "node"`), never
//! an image reference. The profile → image map is owned by the abox release
//! (embedded manifest, `images/manifest.toml`) with a host-config override
//! escape hatch for development (`[images.overrides]` in
//! `~/.abox/config.toml`). Repo config can never choose an image (ADR-008).

use crate::project::EnvironmentProfile;
use anyhow::{Context, Result};
use serde::Deserialize;
use std::collections::HashMap;

/// The manifest embedded at compile time. Regenerated by the image publish
/// workflow, which fills in content digests after each build.
const EMBEDDED_MANIFEST: &str = include_str!("../../../../images/manifest.toml");

/// An OCI image backing a guest profile.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RuntimeImage {
    /// Repository reference without tag/digest, e.g.
    /// `ghcr.io/x-mckay/abox-guest-node`.
    pub reference: String,
    /// Tag used when no digest is pinned yet.
    pub tag: String,
    /// Content digest (`sha256:…`); empty until the image is published.
    pub digest: String,
}

impl RuntimeImage {
    /// The reference to actually pull: digest-pinned when available,
    /// tag-addressed otherwise.
    pub fn pull_reference(&self) -> String {
        // Local rootfs path (development override) — used verbatim.
        if self.reference.starts_with('/') || self.reference.starts_with("./") {
            return self.reference.clone();
        }
        if self.digest.is_empty() {
            format!("{}:{}", self.reference, self.tag)
        } else {
            format!("{}@{}", self.reference, self.digest)
        }
    }

    /// Whether the image is pinned to an exact content digest.
    pub fn is_pinned(&self) -> bool {
        !self.digest.is_empty()
    }
}

#[derive(Debug, Deserialize)]
struct ManifestFile {
    version: u32,
    #[allow(dead_code)]
    release: String,
    profiles: HashMap<String, ManifestProfile>,
}

#[derive(Debug, Deserialize)]
struct ManifestProfile {
    reference: String,
    tag: String,
    #[serde(default)]
    digest: String,
}

/// The parsed profile → image map.
#[derive(Debug, Clone)]
pub struct ImageManifest {
    profiles: HashMap<String, RuntimeImage>,
    /// Host-config development overrides: profile name → full image
    /// reference (used verbatim).
    overrides: HashMap<String, String>,
}

impl ImageManifest {
    /// Parse the manifest embedded in this abox build.
    pub fn embedded() -> Result<Self> {
        Self::parse(EMBEDDED_MANIFEST)
    }

    /// Parse a manifest document.
    pub fn parse(content: &str) -> Result<Self> {
        let file: ManifestFile =
            toml::from_str(content).context("failed to parse image manifest")?;
        anyhow::ensure!(file.version == 1, "unsupported image manifest version {}", file.version);
        let profiles = file
            .profiles
            .into_iter()
            .map(|(name, p)| {
                (name, RuntimeImage { reference: p.reference, tag: p.tag, digest: p.digest })
            })
            .collect();
        Ok(Self { profiles, overrides: HashMap::new() })
    }

    /// Apply host-config overrides (development escape hatch).
    pub fn with_overrides(mut self, overrides: HashMap<String, String>) -> Self {
        self.overrides = overrides;
        self
    }

    /// Resolve the image for a profile.
    ///
    /// A host-config override wins and is used verbatim (unpinned unless the
    /// operator wrote a digest reference). Otherwise the embedded manifest
    /// entry is used. Fails closed if the profile has no mapping.
    pub fn image_for_profile(&self, profile: EnvironmentProfile) -> Result<RuntimeImage> {
        let name = profile.as_str();
        if let Some(reference) = self.overrides.get(name) {
            // A local path override (bind rootfs) is used verbatim.
            if reference.starts_with('/') || reference.starts_with("./") {
                return Ok(RuntimeImage {
                    reference: reference.clone(),
                    tag: String::new(),
                    digest: String::new(),
                });
            }
            let (reference, tag, digest) = split_reference(reference);
            return Ok(RuntimeImage { reference, tag, digest });
        }
        self.profiles.get(name).cloned().ok_or_else(|| {
            anyhow::anyhow!(
                "no guest image mapping for profile '{name}' in this abox build; \
                 add an [images.overrides] entry in ~/.abox/config.toml or upgrade abox"
            )
        })
    }
}

/// Split a user-supplied reference into (repo, tag, digest).
fn split_reference(reference: &str) -> (String, String, String) {
    if let Some((repo, digest)) = reference.split_once('@') {
        return (repo.to_string(), "latest".to_string(), digest.to_string());
    }
    // A ':' after the last '/' is a tag separator (not a registry port).
    let tag_split = match reference.rfind('/') {
        Some(slash) => reference[slash..].rfind(':').map(|i| slash + i),
        None => reference.rfind(':'),
    };
    match tag_split {
        Some(i) => (reference[..i].to_string(), reference[i + 1..].to_string(), String::new()),
        None => (reference.to_string(), "latest".to_string(), String::new()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_manifest_parses_and_covers_all_profiles() {
        let manifest = ImageManifest::embedded().unwrap();
        for profile in [
            EnvironmentProfile::Base,
            EnvironmentProfile::Node,
            EnvironmentProfile::Python,
            EnvironmentProfile::PythonGlibc,
            EnvironmentProfile::Rust,
        ] {
            let image = manifest.image_for_profile(profile).unwrap();
            assert!(
                image.reference.starts_with("ghcr.io/x-mckay/abox-guest-"),
                "unexpected reference for {profile}: {}",
                image.reference
            );
        }
    }

    #[test]
    fn digest_pin_wins_over_tag() {
        let manifest = ImageManifest::parse(
            r#"
            version = 1
            release = "test"
            [profiles.base]
            reference = "example.com/guest"
            tag = "1.0"
            digest = "sha256:abc"
            "#,
        )
        .unwrap();
        let image = manifest.image_for_profile(EnvironmentProfile::Base).unwrap();
        assert!(image.is_pinned());
        assert_eq!(image.pull_reference(), "example.com/guest@sha256:abc");
    }

    #[test]
    fn unpinned_falls_back_to_tag() {
        let manifest = ImageManifest::parse(
            r#"
            version = 1
            release = "test"
            [profiles.base]
            reference = "example.com/guest"
            tag = "1.0"
            "#,
        )
        .unwrap();
        let image = manifest.image_for_profile(EnvironmentProfile::Base).unwrap();
        assert!(!image.is_pinned());
        assert_eq!(image.pull_reference(), "example.com/guest:1.0");
    }

    #[test]
    fn override_wins_and_is_used_verbatim() {
        let manifest = ImageManifest::embedded().unwrap().with_overrides(HashMap::from([(
            "node".to_string(),
            "localhost:5000/dev-guest:latest".to_string(),
        )]));
        let image = manifest.image_for_profile(EnvironmentProfile::Node).unwrap();
        assert_eq!(image.pull_reference(), "localhost:5000/dev-guest:latest");
        assert_eq!(image.reference, "localhost:5000/dev-guest");
    }

    #[test]
    fn override_with_digest() {
        let manifest = ImageManifest::embedded().unwrap().with_overrides(HashMap::from([(
            "base".to_string(),
            "example.com/img@sha256:def".to_string(),
        )]));
        let image = manifest.image_for_profile(EnvironmentProfile::Base).unwrap();
        assert!(image.is_pinned());
        assert_eq!(image.pull_reference(), "example.com/img@sha256:def");
    }

    #[test]
    fn missing_profile_fails_closed() {
        let manifest = ImageManifest::parse("version = 1\nrelease = \"t\"\n[profiles]\n").unwrap();
        assert!(manifest.image_for_profile(EnvironmentProfile::Rust).is_err());
    }

    #[test]
    fn unsupported_version_rejected() {
        assert!(ImageManifest::parse("version = 2\nrelease = \"t\"\n[profiles]\n").is_err());
    }
}
